baseURL = "https://www.pingrunhuang.github.io/"
languageCode = "en-us"
theme = "aafu"
googleAnalytics = "UA-123-45"

[build]
  writeStats = true

[params]
    title = "Frank's blog"
    author = "Frank Huang"
    description = "A safari of me exploring the tech world"
    copyright = "2022-2023"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "pinkish"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Frank Huang"
        tagline = ""
        location = "shenzhen coast city"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/frank-huang-372409105/"
            title = "LinkedIn"		
        #[[params.social.list]]
        #    icon = "fab fa-stack-overflow"
        #    url = "#"
        #    title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/pingrunhuang"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/frank_aico"
            title = "Twitter"
        #[[params.social.list]]
        #    icon = "fab fa-orcid"
        #    url = "#"
        #    title = "Orcid"
        #[[params.social.list]]
        #    icon = "ai ai-google-scholar"
        #    url = "#"
        #    title = "Google Scholar"
        #[[params.social.list]]
        #    icon = "fab fa-researchgate"
        #    url = "#"
        #    title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Hi, I'm Frank from shenzhen China. Currently looking for a remote job in the crypto/AI space"

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "python developer/quant developer(SZ&HK)"
            dates = "2019 - 2023"
            company = "crypto.com"
            details = '''
            1. Built datahub to grab different types of 
                market data from different exchanges through 
                HTTPS and WEBSOCKET.
            2. Using django and huey/Celeory to
                build our middle office platform for 
                trading operation usage.
            '''
        [[params.experience.list]]
            position = "Big data engineer(SZ)"
            dates = "2018 - 2019"
            company = "Cardinal operation"
        [[params.experience.list]]
            position = "data engineer(SZ)"
            location = "shenzhen"
            dates = "2017 - 2018"
            company = "TouchStone"
        [[params.experience.list]]
            position = "Java developer intern(FR Paris)"
            dates = "2016 - 2017"
            company = "Scaled Risk"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.S in Information system"
            college = "ESIGELEC(École Supérieure d'Ingénieurs en Génie Électrique)"
            dates = "2015 - 2017"
            thesis_title = "#"
            thesis_url = "#"
        [[params.education.list]]
            degree = "B.S in Mathematics and applied mathematics(statistics)"
            college = "South China University of Technology"
            dates = "2011 - 2015"
            thesis_title = "#"
            thesis_url = "#"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]
        #[[params.publication.list]]
        #    title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        #    authors = "F Last, F Second, P secondary"
        #    date = "2018"
        #    journal = "Journal of Field 52 (16), 9033-9044"
        #    url = "#"
        #    type = "Journal Articles"
        #[[params.publication.list]]
        #    title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        #    authors = "F Last, F Second, P secondary"
        #    date = "2018"
        #    journal = "Journal of Field 52 (16), 9033-9044"
        #    url = "#"
        #    type = "Journal Articles"
        #[[params.publication.list]]
        #    title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        #    authors = "F Last, F Second, P secondary"
        #    date = "2018"
        #    journal = "Journal of Field 52 (16), 9033-9044"
        #    url = "#"
        #    type = "Proceedings"

    # Project section
    #[params.project]
    #    title = "Projects"
    #    icon = "fas fa-project-diagram"
    #    [[params.project.list]]
    #        title = "Project 1"
    #        url = "#"
    #        description = "Description of the project"
    #    [[params.project.list]]
    #        title = "Project 2"
    #        url = "#"
    #        description = "Description of the project"
    #    [[params.project.list]]
    #        title = "Project 3"
    #        url = "#"
    #        description = "Description of the project"
    #    [[params.project.list]]
    #        title = "Project 4"
    #        url = "#"
    #        description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python"
            skillrating = 80
        [[params.skill.list]]
            skill = "Golang"
            skillrating = 20
        [[params.skill.list]]
            skill = "Javascript"
            skillrating = 20

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Surfing"
        [[params.hobby.list]]
            hobby = "Traveling"